Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 150

Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7.0
  SuggestExtensions: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: [ 'describe', 'context' ]
  Exclude:
    - spec/**/*
    - xxx_rename.gemspec
