#!/usr/bin/env ruby

# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

$pwd = Dir.pwd  # rubocop:disable Style/GlobalVars

require "thor"
require "xxx_rename"

XxxRename::Cli.start ARGV
